// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYZMhWZCFPhwC6HlVaXDoKxbwfuH6JsIY',
    appId: '1:5927054034:web:46a2cd4f074a473b195b0b',
    messagingSenderId: '5927054034',
    projectId: 'kotlin-firebase-503a6',
    authDomain: 'kotlin-firebase-503a6.firebaseapp.com',
    databaseURL: 'https://kotlin-firebase-503a6-default-rtdb.firebaseio.com',
    storageBucket: 'kotlin-firebase-503a6.appspot.com',
    measurementId: 'G-0V3LT9FNGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvqyRx1DSP8KRysiCVEgDbyZ6kCuMNhDY',
    appId: '1:5927054034:android:b1111df9780e7ae1195b0b',
    messagingSenderId: '5927054034',
    projectId: 'kotlin-firebase-503a6',
    databaseURL: 'https://kotlin-firebase-503a6-default-rtdb.firebaseio.com',
    storageBucket: 'kotlin-firebase-503a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN7fz_HK7v5-hBa0UJaJ_I7uo4T1rz4oY',
    appId: '1:5927054034:ios:6e26082065695802195b0b',
    messagingSenderId: '5927054034',
    projectId: 'kotlin-firebase-503a6',
    databaseURL: 'https://kotlin-firebase-503a6-default-rtdb.firebaseio.com',
    storageBucket: 'kotlin-firebase-503a6.appspot.com',
    androidClientId: '5927054034-9k5fpblmkfv2ciphq775ot7ea88tvdko.apps.googleusercontent.com',
    iosClientId: '5927054034-upn8j9kh625p8bi6l0dfhesiig3onird.apps.googleusercontent.com',
    iosBundleId: 'com.davidarturolr.ecostyle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN7fz_HK7v5-hBa0UJaJ_I7uo4T1rz4oY',
    appId: '1:5927054034:ios:8becf9b072687a3d195b0b',
    messagingSenderId: '5927054034',
    projectId: 'kotlin-firebase-503a6',
    databaseURL: 'https://kotlin-firebase-503a6-default-rtdb.firebaseio.com',
    storageBucket: 'kotlin-firebase-503a6.appspot.com',
    androidClientId: '5927054034-9k5fpblmkfv2ciphq775ot7ea88tvdko.apps.googleusercontent.com',
    iosClientId: '5927054034-tvv30q0h2psb6rv4agtvspqfnpoh8n7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecostyle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYZMhWZCFPhwC6HlVaXDoKxbwfuH6JsIY',
    appId: '1:5927054034:web:46a2cd4f074a473b195b0b',
    messagingSenderId: '5927054034',
    projectId: 'kotlin-firebase-503a6',
    authDomain: 'kotlin-firebase-503a6.firebaseapp.com',
    databaseURL: 'https://kotlin-firebase-503a6-default-rtdb.firebaseio.com',
    storageBucket: 'kotlin-firebase-503a6.appspot.com',
    measurementId: 'G-0V3LT9FNGH',
  );
}
