// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN7fz_HK7v5-hBa0UJaJ_I7uo4T1rz4oY',
    appId: '1:5927054034:ios:6e26082065695802195b0b',
    messagingSenderId: '5927054034',
    projectId: 'kotlin-firebase-503a6',
    databaseURL: 'https://kotlin-firebase-503a6-default-rtdb.firebaseio.com',
    storageBucket: 'kotlin-firebase-503a6.appspot.com',
    androidClientId: '5927054034-9k5fpblmkfv2ciphq775ot7ea88tvdko.apps.googleusercontent.com',
    iosClientId: '5927054034-upn8j9kh625p8bi6l0dfhesiig3onird.apps.googleusercontent.com',
    iosBundleId: 'com.davidarturolr.ecostyle',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvqyRx1DSP8KRysiCVEgDbyZ6kCuMNhDY',
    appId: '1:5927054034:android:05678d069ef530db195b0b',
    messagingSenderId: '5927054034',
    projectId: 'kotlin-firebase-503a6',
    databaseURL: 'https://kotlin-firebase-503a6-default-rtdb.firebaseio.com',
    storageBucket: 'kotlin-firebase-503a6.appspot.com',
  );

}